### PR TITLE
Implement move validation for AI

### LINKED ISSUE #20: Check move valid for AI
This could potentially be very complex. May require a path-finding algorithm.

### PR DESCRIPTION
**Pull request by chesterhow**
Wrote basic logic required for monster AI to work given move validation. Whether or not the AI is smart would require more work.

e.g. Since moves are calculated each step at a time, there are times where the AI will simply move left and right and not actually get closer to the player.

Two ways to deal with this:
- Write a path-finding algorithm
- Claim that stupid AI is a feature not a bug

Fixes #20

### CODE REVIEW

**Comment by chesterhow** [comment]
Will shift the AI code into entity in the next PR

**Comment by chesterhow** [comment]
Update: I have moved the AI code to entity class

**Review by ivantjh — APPROVED** [review]

**Comment by ivantjh** [comment]
@chesterhow, i think the next step is to make each enemy distinct and we are almost done, I hope. We can probably do this by overriding the `isValidMove` method on the `entity` class so that certain monsters can travel over certain terrains.

**Comment by chesterhow** [comment]
Yep already did that for ghost

**Pull request merged**
